const buttonEl = document.querySelector("button");
const text = document.querySelector("textarea");
const convertedText = document.querySelector("p");

buttonEl.addEventListener("click", function () {
  const txt = text.value
    .replaceAll("a", "ა")
    .replaceAll("A", "ა")
    .replaceAll("b", "ბ")
    .replaceAll("B", "ბ")
    .replaceAll("c", "ც")
    .replaceAll("C", "ც")
    .replaceAll("d", "დ")
    .replaceAll("D", "დ")
    .replaceAll("e", "ე")
    .replaceAll("E", "ე")
    .replaceAll("f", "ფ")
    .replaceAll("F", "ფ")
    .replaceAll("g", "გ")
    .replaceAll("G", "ღ")
    .replaceAll("h", "ჰ")
    .replaceAll("H", "ჰ")
    .replaceAll("i", "ი")
    .replaceAll("I", "ი")
    .replaceAll("j", "ჯ")
    .replaceAll("J", "ჟ")
    .replaceAll("k", "კ")
    .replaceAll("K", "კ")
    .replaceAll("l", "ლ")
    .replaceAll("L", "ლ")
    .replaceAll("m", "მ")
    .replaceAll("M", "მ")
    .replaceAll("n", "ნ")
    .replaceAll("N", "ნ")
    .replaceAll("o", "ო")
    .replaceAll("O", "ო")
    .replaceAll("p", "პ")
    .replaceAll("P", "პ")
    .replaceAll("q", "ქ")
    .replaceAll("Q", "ქ")
    .replaceAll("r", "რ")
    .replaceAll("R", "ღ")
    .replaceAll("s", "ს")
    .replaceAll("S", "შ")
    .replaceAll("t", "ტ")
    .replaceAll("T", "თ")
    .replaceAll("u", "უ")
    .replaceAll("U", "უ")
    .replaceAll("v", "ვ")
    .replaceAll("V", "ვ")
    .replaceAll("w", "წ")
    .replaceAll("W", "ჭ")
    .replaceAll("x", "ხ")
    .replaceAll("X", "ხ")
    .replaceAll("y", "ყ")
    .replaceAll("Y", "ყ")
    .replaceAll("z", "ზ")
    .replaceAll("Z", "ძ");
  convertedText.textContent = txt;
});
